### PR TITLE
Configure tracker

### PR DESCRIPTION
**Pull request by DuFF14**
More changes to new document on configuring OSVR HMDs with VIVE positional tracking

### CODE REVIEW

**Comment by Balderick** [comment]
Since Valve have hundreds of steamvr tracking HDK partners,  should we be looking at adding steamvr tracking SDK to osvr rather than each individual steamvr tracking device I.e. HTC Tracker?

Great to see a start too steamvr tracking device support being added to osvr.  

Seeing an osvr hdk with integrated steamvr tracking option for consumers  would of course be the best reason to see steamvr tracking support in osvr.

**Comment by DuFF14** [comment]
@Balderick OSVR-Vive already gets tracking data through OpenVR/SteamVR. Is all the new hardware intended to work within the lighthouse system with wireless receivers, identical to the existing controllers and puck? If a new piece of hardware is connected that reports through OpenVR that it is a controller or puck, it should work.

**Comment by Balderick** [comment]
>  Is all the new hardware intended to work within the lighthouse system with wireless receivers, identical to the existing controllers and puck?

Yes.

https://www.triadsemi.com/product/steamvr-tracking-hdk/

https://partner.steamgames.com/vrtracking/


> If a new piece of hardware is connected that reports through OpenVR that it is a controller or puck, it should work.

Cool as.   Thanks for clarifying I just do not have the hardware to test.

Opentrack is how steamvr tracking base stations can be used to track non steamvr tracked devices. 
    https://github.com/opentrack/opentrack

https://www.theverge.com/circuitbreaker/2016/7/6/12109880/htc-vive-lighthouse-hack-diy-positional-tracking

**Comment by DuFF14** [comment]
Then it should be trivial to use those devices instead of the puck in this example. If a new piece of hardware had buttons/analogs/haptics in addition to tracking, it would need a new device descriptor that factors those components into OSVR interfaces.

**Pull request merged**
