### PR TITLE
 Update HDK-Unboxing-and-Getting-Started.md

### PR DESCRIPTION
**Pull request by Balderick**
Trying to add more recent information that is relevant to what everybody sees at http://www.osvr.org/ , expand on info and reorganise info in a reverse chronological order.  i.e. most recent information first

### CODE REVIEW

**Comment by VRguy** [comment]
I would like to leave the section that has the images of the HDK 1.2 and HDK 1.3 because that's the best way of differentiating between them.

Alternatively, perhaps create a new page that shows the various versions of the HDK (1.0 through 1.4, 2.0) and discuss the difference between them both physically (focus and IPD adjustment on 1.0 through 1.2, just focus 1.3 and above; higher resolution and refresh rate on 2.0)

**Comment by Balderick** [comment]
They were moved to bottom of page under "Other Useful Info"  header.   I have not seen that info anywhere else so realised it is still important.   Do you have a link to another source of that information?

> Alternatively, perhaps create a new page that shows the various versions of the HDK (1.0 through 1.4, 2.0) 

Now that sounds like a cunning plan ...    :-)

**Comment by VRguy** [comment]
not quite, but there is still a lot of useful info that you added. Thanks! Let me merge this and then add back some useful info

**Comment by VRguy** [comment]
Thanks very much for your contribution!

**Pull request merged**
